#!/usr/bin/env node
'use strict';

/**
 * Reproducible npm-abandonment census.
 *
 *   node scripts/abandonment-study.js [--vulns] [--out docs/data]
 *
 * Scans a curated set of widely-used / most-depended-on npm packages
 * SEQUENTIALLY (throttled) so npm download counts resolve reliably instead
 * of getting dropped to null under a burst, scores each package with the
 * same engine the CLI ships (cli/lib/scoring.js), and writes:
 *
 *   <out>/abandonment-study.json   raw machine-readable results
 *   <out>/abandonment-study.md     generated summary tables
 *
 * Set GITHUB_TOKEN in the environment to lift the GitHub rate limit and
 * scale PACKAGES to a full top-N census. Everything here is derived from
 * the public npm + GitHub APIs — no inference.
 */

const fs = require('fs');
const path = require('path');
const { getPackageInfo } = require('../cli/lib/api');
const { computeScore } = require('../cli/lib/scoring');
const { queryOSV, summarizeVulns } = require('../cli/lib/osv');

// Curated probe: household-name packages + known-deprecated legends.
// With GITHUB_TOKEN set, replace/extend this with a real most-depended-on list.
const PACKAGES = [
  'moment', 'request', 'underscore', 'q', 'bluebird', 'async', 'mkdirp', 'rimraf',
  'colors', 'gulp', 'grunt', 'bower', 'coffee-script', 'jade', 'through2', 'left-pad',
  'har-validator', 'node-sass', 'optimist', 'faker', 'is-odd', 'tslint', 'protractor',
  'istanbul', 'node-uuid', 'babel-core', 'gulp-util', 'phantomjs', 'request-promise',
  'react', 'express', 'lodash', 'vue', 'axios', 'chalk', 'commander', 'typescript',
  'eslint', 'prettier', 'webpack', 'jest', 'vite', 'next', 'zod', 'dayjs', 'dotenv',
  'uuid', 'semver', 'glob', 'yargs', 'debug', 'body-parser', 'cors', 'ejs',
  'handlebars', 'inquirer', 'minimist', 'jquery'
];

const args = process.argv.slice(2);
const WITH_VULNS = args.includes('--vulns');
const outIdx = args.indexOf('--out');
const OUT_DIR = outIdx >= 0 ? args[outIdx + 1] : path.join(__dirname, '..', 'docs', 'data');

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function scanOne(name) {
  let info = await getPackageInfo(name);
  // One retry if downloads didn't resolve (transient npm rate-limit).
  if (info.downloads == null) {
    await sleep(500);
    try {
      const retry = await getPackageInfo(name);
      if (retry.downloads != null) info = retry;
    } catch (_) { /* keep first result */ }
  }
  const entry = { ...info, ...computeScore(info) };
  if (WITH_VULNS && info.latest) {
    try { entry.vulns = summarizeVulns(await queryOSV(name, info.latest)); }
    catch (_) { entry.vulns = null; }
  }
  return entry;
}

function age(d) {
  if (d == null) return '—';
  if (d >= 365) return (d / 365).toFixed(1) + ' yr';
  if (d >= 30) return Math.round(d / 30) + ' mo';
  return d + ' d';
}
function dl(n) {
  if (n == null) return 'n/a';
  if (n >= 1e6) return (n / 1e6).toFixed(1) + 'M';
  if (n >= 1e3) return Math.round(n / 1e3) + 'k';
  return String(n);
}

(async () => {
  const results = [];
  for (let i = 0; i < PACKAGES.length; i++) {
    const name = PACKAGES[i];
    process.stderr.write(`[${i + 1}/${PACKAGES.length}] ${name}\n`);
    try { results.push(await scanOne(name)); }
    catch (e) { results.push({ name, error: e.message }); }
    await sleep(150);
  }

  const ok = results.filter((r) => !r.error);
  const dead = ok.filter((r) => r.deprecated || r.archived)
    .sort((a, b) => (b.downloads || 0) - (a.downloads || 0));
  const cold = ok.filter((r) => !r.deprecated && !r.archived && (r.daysSincePush || 0) > 365)
    .sort((a, b) => (b.downloads || 0) - (a.downloads || 0));
  const resolved = ok.filter((r) => r.downloads != null);
  const deadDl = dead.filter((r) => r.downloads != null).reduce((s, r) => s + r.downloads, 0);

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const stamp = new Date().toISOString();

  fs.writeFileSync(
    path.join(OUT_DIR, 'abandonment-study.json'),
    JSON.stringify({
      generated_at_utc: stamp,
      tool: 'oss-health-scan',
      authenticated: !!process.env.GITHUB_TOKEN,
      packages: results.length,
      downloads_resolved: resolved.length,
      dead_count: dead.length,
      dead_weekly_downloads: deadDl,
      results
    }, null, 2)
  );

  const ghResolved = ok.filter((r) => r.daysSincePush != null).length;
  const flagOf = (r) => [r.deprecated ? 'deprecated' : null, r.archived ? 'archived' : null].filter(Boolean).join(' + ');

  const md = [];
  md.push('<!-- generated by scripts/abandonment-study.js — do not hand-edit -->');
  md.push('# npm Abandonment — Generated Data');
  md.push('');
  md.push(`_Generated ${stamp} · ${results.length} packages · ${process.env.GITHUB_TOKEN ? 'authenticated' : 'unauthenticated'} run · downloads resolved ${resolved.length}/${ok.length} · GitHub fields resolved ${ghResolved}/${ok.length}._`);
  md.push('');
  md.push(`**${dead.length} of ${ok.length} are deprecated or archived**, moving a combined **~${dl(deadDl)} downloads/week**.`);
  md.push('');
  md.push('## Deprecated or archived');
  md.push('');
  if (ghResolved === 0) {
    md.push('_GitHub-derived fields (push age, archived flag, cold analysis) need `GITHUB_TOKEN`; this run is npm-only._');
    md.push('');
    md.push('| Package | Downloads/wk | Flag | Last npm publish | Health |');
    md.push('|---|--:|---|--:|--:|');
    for (const r of dead) {
      md.push(`| \`${r.name}\` | ${dl(r.downloads)} | ${flagOf(r)} | ${age(r.daysSincePublish)} | ${r.health_score} |`);
    }
  } else {
    md.push('| Package | Downloads/wk | Flag | Last npm publish | Last GitHub push | Health |');
    md.push('|---|--:|---|--:|--:|--:|');
    for (const r of dead) {
      md.push(`| \`${r.name}\` | ${dl(r.downloads)} | ${flagOf(r)} | ${age(r.daysSincePublish)} | ${age(r.daysSincePush)} | ${r.health_score} |`);
    }
    if (cold.length > 0) {
      md.push('');
      md.push('## Cold (no GitHub push in >1 year, not formally flagged)');
      md.push('');
      md.push('| Package | Downloads/wk | Last GitHub push | Health |');
      md.push('|---|--:|--:|--:|');
      for (const r of cold) {
        md.push(`| \`${r.name}\` | ${dl(r.downloads)} | ${age(r.daysSincePush)} | ${r.health_score} |`);
      }
    }
  }
  md.push('');
  fs.writeFileSync(path.join(OUT_DIR, 'abandonment-study.md'), md.join('\n'));

  process.stderr.write(`\nDONE — ${dead.length} dead, ${cold.length} cold, downloads resolved ${resolved.length}/${ok.length}, dead dl/wk=${deadDl}\n`);
})();
