param(
  [string]$OutDir = "evidence",
  [int]$CriticalThreshold = 30,
  [int]$DropThreshold = 10
)

. (Join-Path $PSScriptRoot "common.ps1")

$healthPath = Join-Path $OutDir "health-scores.json"
$trendPath = Join-Path $OutDir "health-trends.json"

if (-not (Test-Path $healthPath)) {
  Write-Host "No health-scores.json found. Skipping alerts."
  exit 0
}

$health = Get-Content $healthPath -Raw | ConvertFrom-Json
$trends = $null
if (Test-Path $trendPath) {
  $trends = Get-Content $trendPath -Raw | ConvertFrom-Json
}

$alerts = @()

# Alert: packages below critical threshold
foreach ($s in $health.scores) {
  if ($s.health_score -lt $CriticalThreshold) {
    $alerts += [PSCustomObject]@{
      type = "critical_health"
      severity = "critical"
      repo = "$($s.owner)/$($s.repo)"
      score = $s.health_score
      message = "Health score $($s.health_score)/100 is below critical threshold ($CriticalThreshold)."
      details = "Maintenance: $($s.breakdown.maintenance.score), Community: $($s.breakdown.community.score), Popularity: $($s.breakdown.popularity.score), Risk: $($s.breakdown.risk.score)"
    }
  }
}

# Alert: score dropped significantly (from trends)
if ($trends -and $trends.trends) {
  foreach ($t in $trends.trends) {
    if ($null -ne $t.delta_7d -and $t.delta_7d -lt (-$DropThreshold)) {
      $alerts += [PSCustomObject]@{
        type = "score_drop"
        severity = "warning"
        repo = $t.repo
        score = $t.current_score
        message = "Health score dropped by $([Math]::Abs($t.delta_7d)) points in 7 days ($($t.score_7d_ago) -> $($t.current_score))."
        details = "Trend: $($t.trend). 30d delta: $($t.delta_30d)"
      }
    }
  }
}

# Write alerts JSON
$alertOutput = [PSCustomObject]@{
  generated_at_utc = ([DateTimeOffset]::UtcNow).UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ssZ")
  total_alerts = $alerts.Count
  critical_alerts = @($alerts | Where-Object { $_.severity -eq "critical" }).Count
  warning_alerts = @($alerts | Where-Object { $_.severity -eq "warning" }).Count
  alerts = $alerts
}

$alertPath = Join-Path $OutDir "alerts.json"
Set-Content -Path $alertPath -Value ($alertOutput | ConvertTo-Json -Depth 8) -Encoding utf8

# Write alerts Markdown
$lines = @()
$lines += "# Health Alerts"
$lines += ""
$lines += "Generated: $($alertOutput.generated_at_utc)"
$lines += "Total: $($alertOutput.total_alerts) (🔴 $($alertOutput.critical_alerts) critical, 🟡 $($alertOutput.warning_alerts) warning)"
$lines += ""

if ($alerts.Count -eq 0) {
  $lines += "✅ No alerts. All packages are within healthy thresholds."
} else {
  $lines += "| Severity | Package | Score | Alert | Details |"
  $lines += "|---|---|---|---|---|"
  foreach ($a in ($alerts | Sort-Object @{ Expression = { if ($_.severity -eq "critical") { 0 } else { 1 } } })) {
    $icon = if ($a.severity -eq "critical") { "🔴" } else { "🟡" }
    $lines += "| $icon $($a.severity) | $($a.repo) | $($a.score)/100 | $($a.message) | $($a.details) |"
  }
}

$mdPath = Join-Path $OutDir "alerts.md"
Set-Content -Path $mdPath -Value ($lines -join "`r`n") -Encoding utf8

# Create GitHub Issue if running in Actions and there are critical alerts
$criticalAlerts = @($alerts | Where-Object { $_.severity -eq "critical" })
if ($env:GITHUB_ACTIONS -and $env:GITHUB_TOKEN -and $criticalAlerts.Count -gt 0) {
  $existingIssues = Get-GitHubJson -Uri "https://api.github.com/repos/$($env:GITHUB_REPOSITORY)/issues?labels=health-alert&state=open"

  # Don't create duplicate issues
  if (@($existingIssues).Count -eq 0) {
    $body = "## ⚠️ Package Health Alert`n`n"
    $body += "The following packages have fallen below the critical health threshold ($CriticalThreshold/100):`n`n"
    foreach ($a in $criticalAlerts) {
      $body += "- **$($a.repo)**: $($a.score)/100 — $($a.message)`n"
      $body += "  - $($a.details)`n"
    }
    $body += "`n*Auto-generated by [oss-maintenance-log](https://github.com/$($env:GITHUB_REPOSITORY))*"

    $issuePayload = @{
      title = "🔴 Health Alert: $($criticalAlerts.Count) package(s) below critical threshold"
      body = $body
      labels = @("health-alert")
    } | ConvertTo-Json -Compress

    try {
      $headers = New-GitHubHeaders
      $headers["Content-Type"] = "application/json"
      Invoke-RestMethod -Uri "https://api.github.com/repos/$($env:GITHUB_REPOSITORY)/issues" `
        -Method Post -Headers $headers -Body $issuePayload | Out-Null
      Write-Host "Created GitHub Issue for $($criticalAlerts.Count) critical alert(s)."
    } catch {
      Write-Warning "Failed to create GitHub Issue: $($_.Exception.Message)"
    }
  } else {
    Write-Host "Open health-alert issue already exists. Skipping."
  }
}

Write-Host "Updated:"
Write-Host " - $alertPath"
Write-Host " - $mdPath"
if ($alerts.Count -gt 0) {
  Write-Warning "$($alerts.Count) alert(s) detected."
}
