'use strict';

// Generate markdown issue drafts for abandoned/critical dependencies.
// Generates only — never files anything. Review before posting.

const { REPLACEMENTS, whyItMatters } = require('./blast');

function issueFor(r) {
  const repl = REPLACEMENTS[r.name];
  const kind = r.deprecated ? 'deprecated' : r.archived ? 'archived' : 'unhealthy';
  const lines = [];
  lines.push(`## Replace ${kind} dependency: \`${r.name}\``);
  lines.push('');
  lines.push(`**Health score:** ${r.health_score}/100 (${r.risk_level})` + (r.blast ? ` · **blast radius:** ${r.blast.level}` : ''));
  lines.push('');
  lines.push('**Why this matters:**');
  for (const w of whyItMatters(r)) lines.push(`- ${w}`);
  lines.push('');
  if (repl) {
    lines.push('**Suggested alternatives:**');
    for (const a of repl) lines.push(`- ${a}`);
  } else {
    lines.push('**Suggested action:** migrate to a maintained alternative, or fork and patch.');
  }
  lines.push('');
  lines.push('<sub>Generated by oss-health-scan — review before filing; suggested alternatives are recommendations, not automatic fixes.</sub>');
  return lines.join('\n');
}

function toIssuesMarkdown(results) {
  const targets = (results || []).filter(r =>
    r.health_score != null && (r.risk_level === 'critical' || r.deprecated || r.archived));
  if (targets.length === 0) return '<!-- no abandoned/critical dependencies found -->\n';
  return targets.map(issueFor).join('\n\n---\n\n') + '\n';
}

module.exports = { toIssuesMarkdown, issueFor };
